export const mockMovies = {
  data: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/tRS6jvPM9qPrrnx2KRp3ew96Yot.jpg",
        genre_ids: [28, 80, 18],
        id: 414906,
        original_language: "en",
        original_title: "The Batman",
        overview:
          "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
        popularity: 82.828,
        poster_path: "/pOaKyhMwALpCTg07eQQu0SQCbL9.jpg",
        release_date: "2022-03-02",
        title: "The Batman",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/2va32apQP97gvUxaMnL5wYt4CRB.jpg",
        genre_ids: [14, 28],
        id: 268,
        original_language: "en",
        original_title: "Batman",
        overview:
          'Batman must face his most ruthless nemesis when a deformed madman calling himself "The Joker" seizes control of Gotham\'s criminal underworld.',
        popularity: 37.444,
        poster_path: "/kbeWnmnHNEnuVej6wcjUv0eY6IL.jpg",
        release_date: "1989-06-23",
        title: "Batman",
        video: false,
        vote_average: 7.2,
        vote_count: 5903,
      },
      {
        adult: false,
        backdrop_path: "/y9AuabF1SXnn3xZ0tAJLLhv33Uj.jpg",
        genre_ids: [28, 80, 18],
        id: 272,
        original_language: "en",
        original_title: "Batman Begins",
        overview:
          "Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
        popularity: 47.351,
        poster_path: "/8RW2runSEc34IwKN2D1aPcJd2UL.jpg",
        release_date: "2005-06-10",
        title: "Batman Begins",
        video: false,
        vote_average: 7.7,
        vote_count: 16935,
      },
      {
        adult: false,
        backdrop_path: "/kU7ZiyeUwcpTkYj3UcxSqGdZmxY.jpg",
        genre_ids: [16, 28],
        id: 618353,
        original_language: "en",
        original_title: "Batman: Death in the Family",
        overview:
          "Tragedy strikes the Batman's life again when Robin Jason Todd tracks down his birth mother only to run afoul of the Joker. An adaptation of the 1988 comic book storyline of the same name.",
        popularity: 111.73,
        poster_path: "/k8Q9ulyRE8fkvZMkAM9LPYMKctb.jpg",
        release_date: "2020-10-13",
        title: "Batman: Death in the Family",
        video: false,
        vote_average: 7.2,
        vote_count: 291,
      },
      {
        adult: false,
        backdrop_path: "/pJS6cZBDKkjh9zPno74EmPErdaw.jpg",
        genre_ids: [878, 80, 16, 9648, 28],
        id: 537056,
        original_language: "en",
        original_title: "Batman: Hush",
        overview:
          "A mysterious new villain known only as Hush uses a gallery of villains to destroy Batman's crime-fighting career as well as Bruce Wayne's personal life, which has been further complicated by a  relationship with Selina Kyle/Catwoman.",
        popularity: 30.78,
        poster_path: "/eiVQORVyVuNNZHPAELuWtlXoQsD.jpg",
        release_date: "2019-07-19",
        title: "Batman: Hush",
        video: false,
        vote_average: 7.3,
        vote_count: 579,
      },
      {
        adult: false,
        backdrop_path: "/rpOqHZMNIaI4qP4r7nw1B7oA0mx.jpg",
        genre_ids: [878, 28, 14],
        id: 415,
        original_language: "en",
        original_title: "Batman & Robin",
        overview:
          "Batman and Robin deal with relationship issues while preventing Mr. Freeze and Poison Ivy from attacking Gotham City.",
        popularity: 25.086,
        poster_path: "/bsg0mrxUKyJoL4oSGP5mlhEsqp.jpg",
        release_date: "1997-06-20",
        title: "Batman & Robin",
        video: false,
        vote_average: 4.3,
        vote_count: 3914,
      },
      {
        adult: false,
        backdrop_path: "/7x4SNxO5HWArighxxFeet5sn3il.jpg",
        genre_ids: [28, 14],
        id: 364,
        original_language: "en",
        original_title: "Batman Returns",
        overview:
          "While Batman deals with a deformed man calling himself the Penguin, an employee of a corrupt businessman transforms into the Catwoman.",
        popularity: 23.072,
        poster_path: "/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg",
        release_date: "1992-06-19",
        title: "Batman Returns",
        video: false,
        vote_average: 6.9,
        vote_count: 4905,
      },
      {
        adult: false,
        backdrop_path: "/jqnbac3oind5VOcAN0mTXyapOGh.jpg",
        genre_ids: [16, 10751, 28, 35, 878, 14],
        id: 324849,
        original_language: "en",
        original_title: "The Lego Batman Movie",
        overview:
          "A cooler-than-ever Bruce Wayne must deal with the usual suspects as they plan to rule Gotham City, while discovering that he has accidentally adopted a teenage orphan who wishes to become his sidekick.",
        popularity: 45.305,
        poster_path: "/snGwr2gag4Fcgx2OGmH9otl6ofW.jpg",
        release_date: "2017-02-08",
        title: "The Lego Batman Movie",
        video: false,
        vote_average: 7.2,
        vote_count: 3917,
      },
      {
        adult: false,
        backdrop_path: "/g2XhZJhFiHcczWcXEEldItG53gd.jpg",
        genre_ids: [878, 28, 12, 16],
        id: 321528,
        original_language: "en",
        original_title: "Batman vs. Robin",
        overview:
          'Damian Wayne is having a hard time coping with his father\'s "no killing" rule. Meanwhile, Gotham is going through hell with threats such as the insane Dollmaker, and the secretive Court of Owls.',
        popularity: 21.337,
        poster_path: "/aGp9XDXmVM5lCKHWtgBC15S7XLr.jpg",
        release_date: "2015-04-14",
        title: "Batman vs. Robin",
        video: false,
        vote_average: 7.3,
        vote_count: 673,
      },
      {
        adult: false,
        backdrop_path: "/dasEWdFNSobYvY8xWcfz3z02kTu.jpg",
        genre_ids: [28, 12, 14],
        id: 209112,
        original_language: "en",
        original_title: "Batman v Superman: Dawn of Justice",
        overview:
          "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
        popularity: 80.679,
        poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
        release_date: "2016-03-23",
        title: "Batman v Superman: Dawn of Justice",
        video: false,
        vote_average: 5.9,
        vote_count: 15326,
      },
      {
        adult: false,
        backdrop_path: "/snlu32RmjldF9b068UURJg8sQtn.jpg",
        genre_ids: [28, 80, 14],
        id: 414,
        original_language: "en",
        original_title: "Batman Forever",
        overview:
          "Batman must battle a disfigured district attorney and a disgruntled former employee with help from an amorous psychologist and a young circus acrobat.",
        popularity: 20.203,
        poster_path: "/mzzNBVwTiiY94xAXDMWJpNPW2US.jpg",
        release_date: "1995-06-16",
        title: "Batman Forever",
        video: false,
        vote_average: 5.4,
        vote_count: 4032,
      },
      {
        adult: false,
        backdrop_path: "/j14Z0pP7tpuHZlVBSuUL7tq2SGb.jpg",
        genre_ids: [16, 9648, 28, 80],
        id: 736074,
        original_language: "en",
        original_title: "Batman: The Long Halloween, Part Two",
        overview:
          "As Gotham City's young vigilante, the Batman, struggles to pursue a brutal serial killer, district attorney Harvey Dent gets caught in a feud involving the criminal family of the Falcones.",
        popularity: 80.045,
        poster_path: "/5X1n5q08mZ7NpNpxehMFODxfNYq.jpg",
        release_date: "2021-07-26",
        title: "Batman: The Long Halloween, Part Two",
        video: false,
        vote_average: 7.7,
        vote_count: 234,
      },
      {
        adult: false,
        backdrop_path: "/uS9apevOgs2fuYghf9szOoK1u63.jpg",
        genre_ids: [16, 9648, 28, 80],
        id: 736073,
        original_language: "en",
        original_title: "Batman: The Long Halloween, Part One",
        overview:
          "Following a brutal series of murders taking place on Halloween, Thanksgiving, and Christmas, Gotham City's young vigilante known as the Batman sets out to pursue the mysterious serial killer alongside police officer James Gordon and district attorney Harvey Dent.",
        popularity: 78.446,
        poster_path: "/sR7gppb0YGjwLvE6Vnj6wYv5MnW.jpg",
        release_date: "2021-06-21",
        title: "Batman: The Long Halloween, Part One",
        video: false,
        vote_average: 7.8,
        vote_count: 284,
      },
      {
        adult: false,
        backdrop_path: "/djBqGjqojpjnacRsRD2dNnvhQbb.jpg",
        genre_ids: [16, 28, 12],
        id: 251519,
        original_language: "en",
        original_title: "Son of Batman",
        overview:
          "Batman learns he has a violent, unruly pre-teen son, secretly raised by the terrorist group known as The League of Assassins.",
        popularity: 23.849,
        poster_path: "/yHx8OLSKc3VtIBB5lIe90c0fHOX.jpg",
        release_date: "2014-05-13",
        title: "Son of Batman",
        video: false,
        vote_average: 7.1,
        vote_count: 785,
      },
      {
        adult: false,
        backdrop_path: "/78WYLdsidjafX5cll2G6fWCR1xB.jpg",
        genre_ids: [10751, 12, 35, 878, 80],
        id: 2661,
        original_language: "en",
        original_title: "Batman",
        overview:
          "The Dynamic Duo faces four super-villains who plan to hold the world for ransom with the help of a secret invention that instantly dehydrates people.",
        popularity: 12.197,
        poster_path: "/zzoPxWHnPa0eyfkMLgwbNvdEcVF.jpg",
        release_date: "1966-07-30",
        title: "Batman",
        video: false,
        vote_average: 6.3,
        vote_count: 595,
      },
      {
        adult: false,
        backdrop_path: "/jvRewPpawHAfBW38EzHoFdTVEez.jpg",
        genre_ids: [16, 28, 12, 80, 14],
        id: 732450,
        original_language: "en",
        original_title: "Batman: Soul of the Dragon",
        overview:
          "Bruce Wayne faces a deadly menace from his past, with the help of three former classmates: world-renowned martial artists Richard Dragon, Ben Turner and Lady Shiva.",
        popularity: 48.231,
        poster_path: "/uDhnTtSxU5a8DtZdbbin3aZmkmU.jpg",
        release_date: "2021-01-12",
        title: "Batman: Soul of the Dragon",
        video: false,
        vote_average: 7,
        vote_count: 197,
      },
      {
        adult: false,
        backdrop_path: "/2JVnUtyUKbQm165cXUF9r5iVPDo.jpg",
        genre_ids: [12, 28, 16, 878],
        id: 408648,
        original_language: "en",
        original_title: "Batman and Harley Quinn",
        overview:
          "Batman and Nightwing are forced to team with the Joker's sometimes-girlfriend Harley Quinn to stop a global threat brought about by Poison Ivy and Jason Woodrue, the Floronic Man.",
        popularity: 20.377,
        poster_path: "/zrqIPpbqCgrs1rS0ltxNicJcuse.jpg",
        release_date: "2017-08-14",
        title: "Batman and Harley Quinn",
        video: false,
        vote_average: 6.2,
        vote_count: 459,
      },
      {
        adult: false,
        backdrop_path: "/nwfpBjtMNFwrGjW2o9HBhMEYCpM.jpg",
        genre_ids: [878, 28, 16],
        id: 366924,
        original_language: "en",
        original_title: "Batman: Bad Blood",
        overview:
          "Bruce Wayne is missing. Alfred covers for him while Nightwing and Robin patrol Gotham City in his stead and a new player, Batwoman, investigates Batman's disappearance.",
        popularity: 20.776,
        poster_path: "/1UmPJWfaivtNjsScJqcsbsQRGNY.jpg",
        release_date: "2016-03-22",
        title: "Batman: Bad Blood",
        video: false,
        vote_average: 7.2,
        vote_count: 595,
      },
      {
        adult: false,
        backdrop_path: "/wNyhtxSazhYVSG1So8zgGTqVFVo.jpg",
        genre_ids: [28, 16, 80, 18],
        id: 382322,
        original_language: "en",
        original_title: "Batman: The Killing Joke",
        overview:
          "As Batman hunts for the escaped Joker, the Clown Prince of Crime attacks the Gordon family to prove a diabolical point mirroring his own fall into madness.",
        popularity: 28.539,
        poster_path: "/nxncAAL1FUKtQWs4uhs5jf1MVut.jpg",
        release_date: "2016-07-24",
        title: "Batman: The Killing Joke",
        video: false,
        vote_average: 6.6,
        vote_count: 1370,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [10751, 16, 35, 9648, 12],
        id: 287757,
        original_language: "en",
        original_title: "Scooby-Doo Meets Batman",
        overview:
          'Scooby-Doo Meets Batman is a video compilation from Warner Bros. Home Entertainment. It consists of two episodes from Hanna-Barbera\'s The New Scooby-Doo Movies, "The Dynamic Scooby Doo Affair" and "The Caped Crusader Caper", where Scooby-Doo and the gang team up with Batman and Robin to capture Joker and the Penguin.',
        popularity: 15.963,
        poster_path: "/uI9enNoQsqseLXQK60YbscDr5L6.jpg",
        release_date: "1972-06-14",
        title: "Scooby-Doo Meets Batman",
        video: true,
        vote_average: 8,
        vote_count: 82,
      },
    ],
    total_pages: 7,
    total_results: 133,
  },
  status: 200,
  statusText: "",
  headers: {
    "cache-control": "public, max-age=600",
    "content-type": "application/json;charset=utf-8",
  },
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false,
    },
    transformRequest: [null],
    transformResponse: [null],
    timeout: 0,
    xsrfCookieName: "XSRF-TOKEN",
    xsrfHeaderName: "X-XSRF-TOKEN",
    maxContentLength: -1,
    maxBodyLength: -1,
    headers: {
      Accept: "application/json, text/plain, */*",
    },
    baseURL: "https://api.themoviedb.org/3",
    params: {
      api_key: "6bc0f2f014d9c75e1a9f43d221494748",
      query: "batman",
    },
    method: "get",
    url: "/search/movie",
  },
  request: {},
};
